### ISSUE TITLE
Update boomerang url

### ISSUE THREAD

**Issue by bluesmoon** [LACNIC/monitor#1]
Hi Agustín, just wanted to thank you for creating this project, and let you know that the boomerang project is now at https://github.com/lognormal/boomerang

We moved it about 4 years ago after I left Yahoo! and at there is no more development happening on the Yahoo! version.  We'd appreciate it if you could update the URL in your project description.

Thanks,

Philip

**Comment by aguformoso** [comment]
Sure!

**Comment by bluesmoon** [comment]
Thanks
